### ISSUE TITLE
Parameter files cannot be loaded correctly

### ISSUE THREAD

**Issue by Hanai613** [oedo-sharaq/artemis-oedo#2]
When a steering file includes another yaml file with 'replace' extension multiple times, a parameter file is not correctly replaced from the second inclusion.
Contents of srppac.yaml are following for instance;

```
    - include:
        name: srppac_newproc.inc.yaml
        replace:
          NAME: src1
          CATIDa: 46
          CATIDx: 47
          CATIDy: 48
          AnodeVALIDTIME: [-100000,100000,0]
          VALIDTIME: [-7500,-5000,0]
          NS2FCPRM: prm/srppac/ns2fC_735V12Torr.dat
          NS2NSPRMX: prm/srppac/sr91/ns2ns_x.dat
          NS2NSPRMY: prm/srppac/src1/ns2ns_y_q0q1cut.dat
          BVALUE: 0.9

     - include:
        name: srppac_newproc.inc.yaml
        replace:
          NAME: src2
          CATIDa: 49
          CATIDx: 10
          CATIDy: 51
          AnodeVALIDTIME: [-100000,100000,0]
          VALIDTIME: [-7500,-5000,0]
          NS2FCPRM: prm/srppac/ns2fC_735V12Torr.dat
          NS2NSPRMX: prm/srppac/src1/ns2ns_x_q0q1cut.dat
          NS2NSPRMY: prm/srppac/sr91/ns2ns_y.dat
          BVALUE: 0.9
```

Although a parameter file named 'ns2ns_x_q0q1cut.dat' must be applied In the second inclusion (src2; FE12 downstream), the values written in the 'ns2ns_x.dat', which is included just before (for src1) are accutually loaded.

Please check also

commit b108a4bf71dc0ced9868cc8822eb93f2b72f27bc
